#!/bin/bash

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

location="`pwd $0`"

find "$location/SRSUR1" -name "*.GED" -exec ruby "$location/ReaderTest.rb" -f "{}" \;
find "$location/SRSUR2" -name "*.GED" -exec ruby "$location/ReaderTest.rb" -f "{}" \;
